# Generated by Django 4.0.4 on 2022-05-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_rename_uid_wordnotes_user'),
        ('scoreImprover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cet4study',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.cet4wordsreq'),
        ),
        migrations.AlterField(
            model_name='cet6study',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.cet6wordsreq'),
        ),
    ]
