# Generated by Django 4.0.4 on 2022-06-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_rename_uid_wordnotes_user'),
        ('user', '0024_remove_user_schedual_user_schedule'),
        ('scoreImprover', '0002_alter_cet4study_wid_alter_cet6study_wid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_see_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('examtype', models.CharField(db_column='examType', default='4', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.neepwordsreq')),
            ],
            options={
                'db_table': 'study',
                'managed': True,
            },
        ),
    ]
