# Generated by Django 4.0.3 on 2022-04-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('signIn', models.IntegerField(default=0)),
                ('examType', models.CharField(default='4', max_length=1)),
                ('examDate', models.DateField(default='2022-2-18')),
                ('progress4', models.IntegerField(default=0)),
                ('progress6', models.IntegerField(default=0)),
                ('progressNeep', models.IntegerField(default=0)),
                ('progressLongSentence', models.IntegerField(default=1)),
                ('test', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'feed_back',
            },
        ),
        migrations.CreateModel(
            name='WordStar',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
                ('spelling', models.ForeignKey(db_column='spelling', on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
            options={
                'db_table': 'word_star',
                'unique_together': {('uid', 'spelling')},
            },
        ),
        migrations.CreateModel(
            name='WordSearchHistory',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
                ('spelling', models.ForeignKey(db_column='spelling', on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
            options={
                'db_table': 'word_search_history',
                'unique_together': {('uid', 'spelling')},
            },
        ),
    ]
