# Generated by Django 4.0.3 on 2022-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'feed_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('signin', models.IntegerField(db_column='signIn')),
                ('examtype', models.CharField(db_column='examType', max_length=1)),
                ('examdate', models.DateField(db_column='examDate')),
                ('signupdate', models.DateField(db_column='signUpDate')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordSearchHistory',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('spelling', models.IntegerField()),
            ],
            options={
                'db_table': 'word_search_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStar',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('spelling', models.IntegerField()),
            ],
            options={
                'db_table': 'word_star',
                'managed': False,
            },
        ),
    ]
