# Generated by Django 4.0.3 on 2022-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AlterField(
            model_name='user',
            name='examDate',
            field=models.DateField(default='2022-3-18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='examType',
            field=models.CharField(default='8', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='progressLongSentence',
            field=models.IntegerField(default=0),
        ),
    ]
