# Generated by Django 4.0.3 on 2022-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_test_alter_user_examdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='examDate',
            field=models.DateField(default='2022-2-18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='examType',
            field=models.CharField(default='4', max_length=1),
        ),
    ]
