# Generated by Django 4.0.3 on 2022-04-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_examdate_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='examtype',
            field=models.CharField(db_column='examType', default=4, max_length=1),
        ),
    ]
