# Generated by Django 4.0.3 on 2022-04-10 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_examdate_alter_user_examtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signUpDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='examDate',
            field=models.DateField(default='2022-13-18'),
        ),
    ]
