# Generated by Django 4.0.3 on 2022-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U',
        ),
        migrations.AlterField(
            model_name='user',
            name='examtype',
            field=models.CharField(db_column='examType', default='4', max_length=1),
        ),
    ]
