# Generated by Django 4.0.3 on 2022-04-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_u_alter_user_examtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
