# Generated by Django 4.0.3 on 2022-05-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_name_alter_user_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordSearchHistory',
        ),
        migrations.AlterUniqueTogether(
            name='wordstar',
            unique_together=set(),
        ),
    ]
