# Generated by Django 4.0.3 on 2022-05-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_testforeignkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordStar',
        ),
    ]
