# Generated by Django 4.0.4 on 2022-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_examdate_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='123', help_text="User's password_hash", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default='123', help_text="User's password_salt", max_length=50),
        ),
    ]
