# Generated by Django 4.0.4 on 2022-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_name_alter_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedual',
            field=models.IntegerField(default=30, help_text="User's schedual"),
        ),
    ]
