# Generated by Django 4.0.4 on 2022-05-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_plurality_alter_word_thirdpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordnotes',
            name='wordspelling',
        ),
        migrations.AddField(
            model_name='wordnotes',
            name='spelling',
            field=models.CharField(blank=True, db_column='spelling', max_length=255, null=True),
        ),
    ]
