# Generated by Django 4.0.4 on 2022-05-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_rename_char_set_wordmatcher_char_set_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordNotes',
        ),
    ]
