# Generated by Django 4.0.4 on 2022-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_delete_wordnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, db_column='UID', null=True)),
                ('spelling', models.CharField(blank=True, db_column='spelling', max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_notes',
                'managed': True,
            },
        ),
    ]
