# Generated by Django 4.0.3 on 2022-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cet4WordsReq',
            fields=[
                ('word_rder', models.AutoField(primary_key=True, serialize=False)),
                ('spelling', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cet4_words_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cet6WordsReq',
            fields=[
                ('word_order', models.AutoField(primary_key=True, serialize=False)),
                ('spelling', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cet6_words_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamReq',
            fields=[
                ('examtype', models.CharField(db_column='examType', max_length=1, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LongSentences',
            fields=[
                ('sid', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('contenten', models.CharField(db_column='contentEN', max_length=255)),
                ('explaincn', models.CharField(blank=True, db_column='explainCN', max_length=255, null=True)),
            ],
            options={
                'db_table': 'long_sentences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NeepWordsReq',
            fields=[
                ('word_order', models.AutoField(primary_key=True, serialize=False)),
                ('spelling', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'neep_words_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreimproverNeepStudy',
            fields=[
                ('sid', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('wid', models.CharField(max_length=255)),
                ('last_see_datetime', models.DateTimeField(blank=True, null=True)),
                ('familiarity', models.IntegerField()),
                ('study_progress', models.IntegerField()),
            ],
            options={
                'db_table': 'scoreimprover_neep_study',
                'managed': False,
            },
        ),
    ]
