# Generated by Django 4.0.4 on 2022-05-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0004_rename_improverneepstudy_neepstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cet4Study',
            fields=[
                ('id', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('wid', models.IntegerField(default=0)),
                ('last_see_datetime', models.DateTimeField(blank=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('study_progress', models.IntegerField()),
            ],
            options={
                'db_table': 'cet4_study',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cet6Study',
            fields=[
                ('id', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('wid', models.IntegerField(default=0)),
                ('last_see_datetime', models.DateTimeField(blank=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('study_progress', models.IntegerField()),
            ],
            options={
                'db_table': 'cet6_study',
                'managed': True,
            },
        ),
    ]
