# Generated by Django 4.0.4 on 2022-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0005_cet4study_cet6study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cet4study',
            name='study_progress',
        ),
        migrations.RemoveField(
            model_name='cet6study',
            name='study_progress',
        ),
        migrations.RemoveField(
            model_name='neepstudy',
            name='study_progress',
        ),
        migrations.AlterField(
            model_name='neepstudy',
            name='last_see_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
