# Generated by Django 4.0.4 on 2022-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0008_neepstudy_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neepstudy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
