# Generated by Django 4.0.3 on 2022-05-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0003_improverneepstudy_delete_scoreimproverneepstudy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImproverNeepStudy',
            new_name='NeepStudy',
        ),
    ]
