# Generated by Django 4.0.4 on 2022-05-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_wordnotes_wordspelling_wordnotes_spelling'),
        ('scoreImprover', '0006_remove_cet4study_study_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neepstudy',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.neepwordsreq'),
        ),
    ]
