# Generated by Django 4.0.4 on 2022-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_wordnotes_wordspelling_wordnotes_spelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=255)),
                ('char_set', models.CharField(max_length=26)),
            ],
        ),
    ]
