# Generated by Django 4.0.3 on 2022-04-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordspelling', models.CharField(blank=True, db_column='wordSpelling', max_length=255, null=True)),
                ('uid', models.IntegerField(blank=True, db_column='UID', null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty_rate', models.IntegerField(blank=True, db_column='difficulty_rate', null=True)),
            ],
            options={
                'db_table': 'word_notes',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('spelling', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('explaincn', models.CharField(blank=True, db_column='explainCN', max_length=255, null=True)),
                ('explainen', models.CharField(blank=True, db_column='explainEN', max_length=255, null=True)),
                ('plurality', models.CharField(blank=True, max_length=255, null=True)),
                ('pasttense', models.CharField(blank=True, db_column='pastTense', max_length=255, null=True)),
                ('presentparticiple', models.CharField(db_column='presentParticiple', max_length=255)),
                ('pastparticiple', models.CharField(blank=True, db_column='pastParticiple', max_length=255, null=True)),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='NeepWordsReq',
            fields=[
                ('wordorder', models.AutoField(db_column='wordOrder', primary_key=True, serialize=False)),
                ('spelling', models.ForeignKey(db_column='spelling', on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
            options={
                'db_table': 'neep_words_req',
            },
        ),
        migrations.CreateModel(
            name='Cet6WordsReq',
            fields=[
                ('wordorder', models.AutoField(db_column='wordOrder', primary_key=True, serialize=False)),
                ('spelling', models.ForeignKey(db_column='spelling', on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
            options={
                'db_table': 'cet6_words_req',
            },
        ),
        migrations.CreateModel(
            name='Cet4WordsReq',
            fields=[
                ('wordorder', models.AutoField(db_column='wordOrder', primary_key=True, serialize=False)),
                ('spelling', models.ForeignKey(db_column='spelling', on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
            options={
                'db_table': 'cet4_words_req',
            },
        ),
    ]
