# Generated by Django 4.0.3 on 2022-04-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wordnotes',
            options={'managed': True},
        ),
    ]
