# Generated by Django 4.0.4 on 2022-05-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_options_alter_wordnotes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='plurality',
            field=models.CharField(blank=True, help_text='noun plural', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='thirdpp',
            field=models.CharField(blank=True, help_text='3rd person present', max_length=255, null=True),
        ),
    ]
