# Generated by Django 4.0.3 on 2022-04-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinfo_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='U',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name_id', max_length=20)),
                ('signin', models.IntegerField(db_column='signIn', default=0)),
                ('examtype', models.CharField(db_column='examType', default=4, max_length=1)),
                ('examdate', models.DateField(db_column='examDate', default='1970-01-01', null=True)),
                ('signupdate', models.DateField(db_column='signUpDate', default='1970-01-01')),
            ],
            options={
                'db_table': 'U',
                'managed': True,
            },
        ),
    ]
