# Generated by Django 4.0.3 on 2022-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='signin',
            field=models.IntegerField(db_column='signIn', default=0, help_text='the sign in days >=0'),
        ),
    ]
