# Generated by Django 4.0.3 on 2022-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_wordsearchhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.IntegerField()),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_search_history', to='user.user')),
            ],
            options={
                'db_table': 'word_search_history',
                'managed': True,
            },
        ),
    ]
