# Generated by Django 4.0.3 on 2022-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_wordsearchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.DeleteModel(
            name='WordStar',
        ),
    ]
