# Generated by Django 4.0.3 on 2022-05-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_wordstar_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsearchhistory',
            name='spelling',
            field=models.CharField(default='application', max_length=25),
        ),
        migrations.AlterField(
            model_name='wordstar',
            name='spelling',
            field=models.CharField(default='application', max_length=25),
        ),
    ]
