# Generated by Django 4.0.3 on 2022-05-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_wordstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(default='application', max_length=25)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_word_star', to='user.user')),
            ],
            options={
                'db_table': 'word_star',
                'managed': True,
            },
        ),
    ]
