# Generated by Django 4.0.4 on 2022-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_wordstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signupdate',
            field=models.DateField(auto_now_add=True, db_column='signUpDate'),
        ),
    ]
