# Generated by Django 4.0.4 on 2022-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='examdate',
            field=models.DateField(db_column='examDate', default='1970-01-01', help_text="User's exam date"),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name_id', help_text="User's name", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default=None, help_text="User's openid", max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signupdate',
            field=models.DateField(auto_now_add=True, db_column='signUpDate', help_text="User's sign up date"),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
