# Generated by Django 4.0.4 on 2022-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name_id', help_text="User's name", max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='123', help_text="User's password_hash", max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default='123', help_text="User's password_salt", max_length=250),
        ),
    ]
