# Generated by Django 4.0.4 on 2022-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_schedual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedual',
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.IntegerField(default=30, help_text="User's schedule"),
        ),
    ]
