# Generated by Django 4.0.4 on 2022-05-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0018_user_openid'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReq',
            fields=[
                ('examtype', models.CharField(db_column='examType', max_length=1, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_req',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LongSentences',
            fields=[
                ('sid', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('contenten', models.CharField(db_column='contentEN', max_length=255)),
                ('explaincn', models.CharField(blank=True, db_column='explainCN', max_length=255, null=True)),
            ],
            options={
                'db_table': 'long_sentences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NeepStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_see_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.neepwordsreq')),
            ],
            options={
                'db_table': 'neep_study',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cet6Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_see_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.neepwordsreq')),
            ],
            options={
                'db_table': 'cet6_study',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cet4Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_see_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('familiarity', models.IntegerField(default=0, help_text='熟练度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.neepwordsreq')),
            ],
            options={
                'db_table': 'cet4_study',
                'managed': True,
            },
        ),
    ]
