# Generated by Django 4.0.3 on 2022-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReq',
            fields=[
                ('examtype', models.CharField(db_column='examType', max_length=1, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_req',
            },
        ),
        migrations.CreateModel(
            name='LongSentences',
            fields=[
                ('sid', models.IntegerField(db_column='SID', primary_key=True, serialize=False)),
                ('contenten', models.CharField(db_column='contentEN', max_length=255)),
                ('explaincn', models.CharField(blank=True, db_column='explainCN', max_length=255, null=True)),
            ],
            options={
                'db_table': 'long_sentences',
            },
        ),
    ]
