# Generated by Django 4.0.3 on 2022-04-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cet4WordsReq',
        ),
        migrations.DeleteModel(
            name='Cet6WordsReq',
        ),
        migrations.DeleteModel(
            name='NeepWordsReq',
        ),
        migrations.AlterModelOptions(
            name='examreq',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='longsentences',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scoreimproverneepstudy',
            options={'managed': True},
        ),
    ]
