# Generated by Django 4.0.4 on 2022-05-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_wordstar'),
        ('scoreImprover', '0007_alter_neepstudy_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='neepstudy',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
            preserve_default=False,
        ),
    ]
