# Generated by Django 4.0.4 on 2022-05-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreImprover', '0009_alter_neepstudy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neepstudy',
            old_name='uid',
            new_name='user',
        ),
    ]
